name: AMER/EU Unpublish Past Events
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '10 22 * * *' #  run at 5:10PM for Americas and Europe
  workflow_dispatch:

jobs:
  unpublish:
    environment:
      name: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run Script
        id: unpublish-script
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        uses: actions/github-script@v7
        with:
          script: |
            const { default: unpublishPastEvents } = await import('${{ github.workspace }}/scripts/unpublish-pages.mjs')

            const response = await unpublishPastEvents(process.env.AUTH_TOKEN, "AMER")
            core.setOutput("subject", response.subject)
            core.setOutput("body", response.body)
            return response
          result-encoding: string
      - name: Send Email Notifications
        uses: cinotify/github-action@main
        with:
          to: 'laurel.timko@jmp.com'
          subject: "${{steps.unpublish-script.outputs.subject}}"
          body: "${{steps.unpublish-script.outputs.body}}"
          type: 'text/html'
